let lifes = 3;
let time = 30;
const life1 = document.getElementById('life1-el');
const life2 = document.getElementById('life2-el');
const life3 = document.getElementById('life3-el');
let points = 0;
let question1 = false;
let question2 = false;
let question3 = false;
let question4 = false;
let question5 = false;
let question6 = false;
let question7 = false;
let question8 = false;
let question9 = false;
let question10 = false;
const questionDisplay = document.getElementById('question-el')
const nextQuestionDisplay = document.getElementById('next-question');
const answer1 = document.getElementById('a1');
const answer2 = document.getElementById('a2');
const answer3 = document.getElementById('a3');
const answer4 = document.getElementById('a4');
const correctAnswer = ["Well done!", "Great job on that one!", "Excellent"];
const wrongAnswer = ["Maybe study a little more", "That was a tough one", "Better luck next time"]
const allCorrect = "Wow you got them all right! Looks like your a Javascript Dev!";
const halfCorrect = "You did good! But there's a little to study up on";
const noneCorrect = "Don't get disheartened! Just practise and try again!";